name: Production Deploy

on:
  push:
    tags:
      - "release*"
  workflow_run:
    workflows: [Make Release]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main:
    if: ${{ github.event_name == 'push' || github.event.workflow_run.conclusion == 'success' }}
    name: Deployment
    runs-on: ubuntu-latest
    environment:
      name: production
      url: 'https://example.com'
    steps:
    - name: Simulate Delay
      run: sleep 120
    - name: Send greeting
      run: echo "Simulated Deploy https://github.com/gotbadger/workflow-test/releases/latest"
