name: Production Deploy

on:
  push:
    tags:
      - "*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main:
    name: Deployment
    runs-on: ubuntu-latest
    environment:
      name: production
      url: 'https://my.bearer.sh'
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Simulated Deploy"