name: Production Deploy

on:
  push:
    tags:
      - "release*"
  workflow_run:
    workflows: [Make Release]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main:
    name: Deployment
    runs-on: ubuntu-latest
    environment:
      name: production
      url: 'https://my.bearer.sh'
    steps:
    - name: Simulate Delay
      run: sleep 120
    - name: Send greeting
      run: echo "Simulated Deploy"