name: Extract Meta
on:
  workflow_dispatch:


jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: default-branch-name
        shell: bash
        run: |
          echo ${{ github.event.repository.default_branch }}
      - id: sha
        shell: bash
        run: |
          echo ${{github.sha}}
      - id: current-branch-name
        shell: bash
        run: |
          echo ${{github.ref_name}}
     - id: repo_url
        shell: bash
        run: |
          echo ${{github..event.repository.repository_url}}
