name: "PR Number"
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
      
permissions:
  contents: read

jobs:
  number:
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ github.event.pull_request.number || github.event.issue.pull_request }}
      SHA: ${{ github.event.pull_request.head.sha || github.sha }}
    steps:
      - name: "check PR_NUMBER"
        run: echo "Value is $PR_NUMBER"
      - name: "check SHA"
        run: echo "Value is $SHA"
