name: "PR Number"
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
      
permissions:
  contents: read

jobs:
  number:
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ github.event.pull_request.number }}
    steps:
      - name: "check contents"
        run: echo "Value is $PR_NUMBER"
