name: tag
on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  tag:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: release-v
          default_bump: patch
    outputs:
      tag_name: ${{ steps.tag_version.outputs.new_tag }}

  display-version:
    needs: [tag]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ needs.tag.outputs.tag_name || github.ref }}
      - run: git fetch --force --tags
      - name: status
        run: git status