name: tag
on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Bump version and push tag
        if: github.ref == 'refs/heads/main'
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: release-v
          default_bump: patch
    outputs:
      tag_name: ${{ steps.tag_version.outputs.new_tag || github.ref }}

  display-version:
    needs: [tag]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ needs.tag.outputs.tag_name }}
      - run: git fetch --force --tags
      - run: git status
      - run: echo "${{ needs.tag.outputs.tag_name }}"